<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ConnectAi.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
	<PackageReference Include="Pgvector" Version="0.3.1" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\8i8.Domain\8i8.Domain.csproj" />
  </ItemGroup>

</Project>
